substitutions:
  name: bluesmart-charger
  external_components_source: github://KinDR007/VictronMPPT-ESPHOME@main

esphome:
  name: ${name}
  min_version: 2024.6.0

esp32:
  board: esp32dev

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  baud_rate: 0

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

# api:

uart:
  id: uart_0
  tx_pin: GPIO16  # Not connected! The communication is read-only
  rx_pin: GPIO17  # Connect this this GPIO and GND to the charger
  baud_rate: 19200
  rx_buffer_size: 256

victron:
  uart_id: uart_0
  id: victron0
  throttle: 10s

sensor:
  - platform: victron
    victron_id: victron0
    battery_voltage:
      name: "${name} output voltage"
    battery_current:
      name: "${name} current"
    error_code:
      name: "${name} error code"
    charging_mode_id:
      name: "${name} mode id"

text_sensor:
  - platform: victron
    victron_id: victron0
    device_type:
      name: "${name} device type"
    firmware_version_24bit:
      name: "${name} firmware version"
    serial_number:
      name: "${name} serial number"
    hardware_revision:
      name: "${name} hardware number"
    error:
      name: "${name} error"
    charging_mode:
      name: "${name} charging mode"
