substitutions:
  name: phoenix-inverter
  external_components_source: github://KinDR007/VictronMPPT-ESPHOME@main

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
# api:

logger:
  baud_rate: 0
  esp8266_store_log_strings_in_flash: false

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

uart:
  id: uart_0
  tx_pin: D8  # Not connected! The communication is read-only
  rx_pin: D7  # Connect this this GPIO and GND to the MPPT charger
  baud_rate: 19200
  rx_buffer_size: 256

victron:
  uart_id: uart_0
  id: victron0
  throttle: 10s

sensor:
  - platform: victron
    victron_id: victron0
    battery_voltage:
      name: "${name} battery voltage"
    battery_current:
      name: "${name} battery current"
    charging_mode_id:
      name: "${name} charging mode id"
    device_mode_id:
      name: "${name} device mode id"
    ac_out_voltage:
      name: "${name} ac out voltage"
    ac_out_current:
      name: "${name} ac out current"
    ac_out_apparent_power:
      name: "${name} ac out apparent power"
    warning_code:
      name: "${name} warning code"
    off_reason_bitmask:
      name: "${name} off reason bitmask"

text_sensor:
  - platform: victron
    victron_id: victron0
    alarm_reason:
      name: "${name} alarm reason"
    # TODO: "OR"
    charging_mode:
      name: "${name} charging mode"
    firmware_version:
      name: "${name} firmware version"
    device_type:
      name: "${name} device type"
    serial_number:
      name: "${name} serial number"
    device_mode:
      name: "${name} device mode"
    warning:
      name: "${name} warning"
    off_reason:
      name: "${name} off reason"

binary_sensor:
  - platform: victron
    victron_id: victron0
    relay_state:
      name: "${name} relay state"
